WIP - [Functions] Debugging support for isolated worker
JetBrains/azure-tools-for-intellij pull request #483
Opened 2021-04-27 13:28 UTC by maartenba

Part of #413, and provides:
* Debugging support for isolated worker runtime

This PR is a work in progress. Opening it now for initial feedback from @sdubov and @ArsenyChernyaev (comments welcome)

Needs:
* More tests and logging
* Right now detecting runtime type on front-end, might move it to back-end as we already have a check there based on referenced NuGet packages

2021-04-30 09:38 UTC, sdubov requested changes

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettings.kt
> +                    else -> FunctionsWorkerRuntime(value)
What is the use case of having a random runtime here?

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettings.kt
> +data class FunctionsWorkerRuntime(val value: String) {
Isn't it better to have an enum class for this purpose since we have two concrete options?
```
enum class FunctionsWorkerRuntime(val value: String) {
  DotNetDefault("dotnet"),
  DotNetIsolated("dotnet-isolated")
}
```

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +        pumpMessages(Duration.ofMinutes(5)) {
Hm... 5 min, do you think it isn't too much?

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +            // REVIEW: If we do not get pid from the isolated worker process, should we destroy the process here?
I think we need to notify a user about this via Notification like you do below and log this event. Regarding the further action - I think we have no option to attach to the process without PID and since we run the process from an action that start a debugger, then I think termination is the right action.

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +            // REVIEW: Should we throw here instead?
I think we need to do both (show notification and throw). No need to proceed with PID = 0

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreRuntime.kt
> +            FunctionsWorkerRuntime.DotNetDefault -> AzureFunctionsDotNetCoreDebugProfile(dotNetExecutable, executionEnvironment, coreToolsInfo.coreToolsExecutable, coreToolsInfo.coreToolsPath)
`coreToolsInfo.coreToolsPath` is unused variable inside `AzureFunctionsDotNetCoreDebugProfile`.

2021-04-30 09:38 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +        logger.info("Functions host process started: $commandLineString")
`ProcessAdapter` has override for fun `startNotified(event: ProcessEvent)`. Maybe move the "started message" under this event? I would like to log a `commandLine` here though.

2021-04-30 09:40 UTC, sdubov requested changes

2021-04-30 09:40 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +    override val attached: Boolean = false
@ArsenyChernyaev, @maartenba, do you know why do we use this flag?

2021-04-30 11:00 UTC, maartenba commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettings.kt
> +data class FunctionsWorkerRuntime(val value: String) {
Had that originally, will revert.

2021-05-02 10:40 UTC, maartenba commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettings.kt
> +                    else -> FunctionsWorkerRuntime(value)
Updated to an enum now.

2021-05-02 10:41 UTC, maartenba commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +        pumpMessages(Duration.ofMinutes(5)) {
Updated to 2 minutes. Still long, but taking into account that on Windows you may need to allow firewall rules it's not bad to have it on the longer side. Any thoughts on what a better value would be?

2021-05-03 09:10 UTC, sdubov commented on PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt
> +        pumpMessages(Duration.ofMinutes(5)) {
cc @ArsenyChernyaev ^^^?

2021-05-03 09:11 UTC, sdubov approved these changes
LGTM

2021-05-03 12:37 UTC, maartenba commented
Thanks, merging!

2021-05-03 12:37 UTC, merged